### PR TITLE
Drop any log events coming from the Raven package

### PR DESCRIPTION
**Pull request by tootedom**
Hi there,

If Raven ever happens to log during its operation whilst trying to send an event called by the SentryAppender, a situation could occur where the appender's queue is full and so by trying to log another message, you deadlock Logback.

This PR prevents any messages from the `net.kencochrane.raven` package from being sent to the SentryAppender thus preventing any potential deadlock. It does not prevent these messages from being sent to any other appenders so if you e.g. had a `FileAppender` configured then the Raven errors would still be logged there.

Here's a stack trace of the pertinent issue:

```
"AsyncAppender-Worker-Thread-2" #12 daemon prio=5 os_prio=31 tid=0x00007f891d0f4800 nid=0x5d03 waiting on condition [0x0000000121352000]
   java.lang.Thread.State: WAITING (parking)
    at sun.misc.Unsafe.park(Native Method)
    - parking to wait for  <0x00000006c00cd2b8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
    at java.util.concurrent.ArrayBlockingQueue.put(ArrayBlockingQueue.java:353)
    at ch.qos.logback.core.AsyncAppenderBase.put(AsyncAppenderBase.java:139)
    at ch.qos.logback.core.AsyncAppenderBase.append(AsyncAppenderBase.java:130)
    at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:88)
    at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:48)
    at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:273)
    at ch.qos.logback.classic.Logger.callAppenders(Logger.java:260)
    at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:442)
    at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:396)
    at ch.qos.logback.classic.Logger.error(Logger.java:559)
    at net.kencochrane.raven.Raven.sendEvent(Raven.java:64)
    at net.kencochrane.raven.logback.SentryAppender.append(SentryAppender.java:132)
    at net.kencochrane.raven.logback.SentryAppender.append(SentryAppender.java:24)
    at ch.qos.logback.core.AppenderBase.doAppend(AppenderBase.java:85)
    - locked <0x00000006c00cca18> (a net.kencochrane.raven.logback.SentryAppender)
    at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:48)
    at ch.qos.logback.core.AsyncAppenderBase$Worker.run(AsyncAppenderBase.java:226)
```

Additionally whilst testing this code we noticed a bug where the `ThresholdFilter` wasn't attached to the correct appender so we fixed that as well.

thanks
@joerayme + @tootedom

### CODE REVIEW

**Comment by stve** [comment]
Thanks for the PR

Nice catch on the `ThresholdFilter`

Does it makes sense for this library to implement a filter on `net.kencochrane.raven` or is that something that should be the responsibility of raven-logback? (if thats even possible)

**Comment by tootedom** [comment]
Hi there,

Yup it absolutely makes sense for raven-logback to sort this out.  However, I'm not sure they will be able to.  I've opened an issue with them: https://github.com/getsentry/raven-java/issues/151

The difficulty is that in traditional logback you can filter which Appender that packages can log to.  However, currently in drop wizard this is not possible (it may be coming, https://github.com/dropwizard/dropwizard/pull/1092 , but it's hard to decipher if that will allow it).  

As a result the only way to stop a log message going to the SentryAppender from the `net.kencochrame.raven` package, but still have the message logged the file appender in drop wizard, is to have this custom filter.  Without the this filter, the deadlock occurs.

Hope that makes sense
/dom

**Comment by stve** [comment]
Makes perfect sense, thanks for the detailed explanation. I'll follow the issues referenced above and if this ends up being resolved upstream we can adjust the implementation here as needed. 

Would you mind splitting out `ThresholdFilter` change into a separate commit (or separate PR) so that the changes are isolated?

Thanks :smile:

**Comment by stve** [comment]
@tootedom don't worry about the `ThresholdFilter`, I am going to tweak slightly so decided to merge. Thanks for the PR. :smile:

**Comment by tootedom** [comment]
Thanks,
/dom

**Pull request merged**
